### ISSUE TITLE
Subtract 2 STL files

### ISSUE THREAD

**Issue by copperwr** [WoLpH/numpy-stl#105]
Hi there, 

I already use numpy-stl to generate STL files and it works great.

What I need to be able to do is to load up 2 STL files and substract one from the other.  

Could this be supported by numpy-stl?

Thanks for any thoughts on this..
Robert

**Comment by WoLpH** [comment]
It's definitely not within the current list of features. There are very few manipulation features in the library at this moment since the main purpose is simply loading/saving STL files, not manipulating the mesh.

You can see the methods in the docs. There are methods for rotating and translating for example, but subtracting is ambiguous by definition. It could mean mathematically subtracting or cutting a hole in one of the objects.
Either way, all built-in manipulations can be found on this page: https://numpy-stl.readthedocs.io/en/latest/stl.html
