### ISSUE TITLE
I have rotated the model, but the result is a little bit wired

### ISSUE THREAD

**Issue by Nightmareone** [WoLpH/numpy-stl#109]
I have tried to rotate the model in 360 degree, But the result is defferent from the result before rotating, Is there any problem with my code? or can you tell me why I got this result.....Thank you.

### code
```
    list_x = []
    list_y = []
    list_z = []
    your_mesh = mesh.Mesh.from_file(filename)
    for v in your_mesh.data:
        list_x.append(v[1][0][0])
        list_x.append(v[1][1][0])
        list_x.append(v[1][2][0])

        list_y.append(v[1][0][1])
        list_y.append(v[1][1][1])
        list_y.append(v[1][2][1])
    
    min_x = min(list_x)
    max_x = max(list_x)
    min_y = min(list_y)
    max_y = max(list_y)

    print("max_x:" + str(max_x) + "; min_x:" + str(min_x))
    print("max_y:" + str(max_y) + "; min_y:" + str(min_y))
    print('===========================================')
    angle = -360
    your_mesh.rotate([0.0, 0.0, 1.0], math.radians(angle))
    for v in your_mesh.data:
        list_x.append(v[1][0][0])
        list_x.append(v[1][1][0])
        list_x.append(v[1][2][0])

        list_y.append(v[1][0][1])
        list_y.append(v[1][1][1])
        list_y.append(v[1][2][1])
    
    min_x = min(list_x)
    max_x = max(list_x)
    min_y = min(list_y)
    max_y = max(list_y)

    print("max_x:" + str(max_x) + "; min_x:" + str(min_x))
    print("max_y:" + str(max_y) + "; min_y:" + str(min_y))
```
### result
![キャプチャ2](https://user-images.githubusercontent.com/7871291/62680262-c7b07d00-b9f1-11e9-866e-209a9ac14044.PNG)
By the way, I'm doing research using STL file, numpy-stl really helped me a lot.**Thank you for your job**.

**Comment by Uvar** [comment]
So instead of 0, you get after a floating point operation the number `0.00000000000000734788`
which is on the order of `2*2^(-48)` deviation from zero. On a certain scale, you are doing `1.5*1.5 = 2*2 = 4` while expecting the outcome to be `2`. It's just that the scale is far smaller than these 1 decimal problems.

It's actually a well-known phenomenon while doing floating point arithmetic, and I can not describe any part of it better than has been described in [Appendix D of the Numerical Computation guide](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)

**Comment by WoLpH** [comment]
I believe @Uvar is right, it looks like floating point errors.

With certain numbers you'll always get these due to how floating point numbers are stored (`significand * base ^ exponent`).

For example:
```python
In [1]: 0.1 + 0.2
Out[1]: 0.30000000000000004

In [2]: total = 0.0

In [3]: for i in range(10):
   ...:     total += 0.1
   ...:

In [4]: total
Out[4]: 0.9999999999999999
```

**Comment by Nightmareone** [comment]
Thank you so much, @Uvar , @WoLpH !! I have understood it, and solve the problem!!
