### ISSUE TITLE
Feature request: unify duplicated vertices

### ISSUE THREAD

**Issue by Skylion007** [WoLpH/numpy-stl#12]
This is really just a space optimization, but when you create an STL file, it does not unify the vertices so you have a lot of duplicated data. I have to open all the files in meshlab to compress the stl file like so. It would be a handy function to implement in this library especially if you are generating a ton of STL files.

**Comment by WoLpH** [comment]
Well, there is a method to delete duplicate polygons, that could help a bit? http://numpy-stl.readthedocs.org/en/latest/stl.html#stl.base.BaseMesh.remove_duplicate_polygons

Usage example: https://github.com/WoLpH/numpy-stl/blob/master/tests/test_mesh.py#L59-L96

Beyond that, what kind of unification are you looking for?

**Comment by Skylion007** [comment]
I assume it means in the STL, you only need to reference each vertice once and then call it by index at a later time. I don't know much about the STL format, but the Collada file format does have such a feature. All I know is that every time I open an STL generated with this program even after running remove duplicate polygons, it asks if I would like to "unify" vertices. The number of vertices mesh then decreases and the file size becomes smaller.

**Comment by WoLpH** [comment]
In that case I would need to see the before and after file to see what it actually removes. Perhaps the feature can be easily integrated.

There are some features planned to clean up STL files in the future but they're just on the drawingboard currently. It will take some time before they're actually here.

**Comment by Skylion007** [comment]
Fair enough, I just wanted to put a feature request in for that. Also, I would like to add another I've just discovered while using it. Mesh.save does not seem to like absolute paths. Ideally, it should support absolute paths so that you do not have change working directories every time you want to save a stl file in a different folder. 

Other than that, great library. Simple and effective.

**Comment by WoLpH** [comment]
Can't say I can reproduce the absolute path issue, can you open an issue with the stacktrace?

**Comment by Skylion007** [comment]
Funny thing, it didn't leave a stack trace. It just seemed to truncate everything before the last /. Eg when I saved it something like /home/my-username/project/output.stl it would just save to my current working directory instead. In fact, if I changed the current working directory to project, saved the stl with the absolute path it worked, but not if I specified any other folder absolutely. I am also running Linux so I am not sure if this a bug that only affects Unix style file paths.

**Comment by WoLpH** [comment]
Hmm... you're right. Never tried that, I've just fixed it in https://github.com/WoLpH/numpy-stl/tree/v1.5.2 :)

**Comment by Uvar** [comment]
Are you certain that it reduces the data?
I just tried it on one of my STL files. The ''reduction'' in data was 6 kB on a 3MB file, while the reduction in internal representation of vertices was approximately a factor 6. It is inherently impossible to reduce data in this way in a STL definition, because well yeah..STL accepts redundancy in favour of ease of application.
It might be handy for further operations/calculations performed on the mesh, so it is still a neat utility in the end, just not for the sake of disk space usage optimization.

**Comment by WoLpH** [comment]
It took a bit of searching but I've found the source of the RemoveDuplicateVertex function in Meshlab. Looks like it's using the clean module of vcglib: http://vcg.isti.cnr.it/vcglib/clean_8h_source.html#l00142

Unfortunately they appear to have no documentation so I'll need to look through the source to see what it does. Not impossible but it will take a bit of time and I'm fairly busy at the moment :)

**Comment by Uvar** [comment]
What would actually be the use of this feature? Further use, or compressibility (the latter of which is not feasible)?

Unless some more information is provided, I'm afraid none of us will be able to correctly address the issue.

**Comment by Skylion007** [comment]
I believe it is the latter. I personally do not have too much of an investment in this feature; it just appears as though other 3D modelling software finds the meshes rather messy. The repo works fine as is and this would be a nice feature to have, but in no way necessary.

**Comment by WoLpH** [comment]
Well, I've had a look at what meshlab produces and it seems that the STL files are pretty much identical. The issue here is that the STL format is inherently suboptimal when compared to PLY or other formats. Meshlab can internally reduce the memory usage and the meshes to something that is faster to process, but the output STL remains the same. Effectively, nothing changes within a single object.

I'll keep this feature in the back of my mind in case we are ever going to add some more modification features as rotations/translations/etc. This would definitely be faster for smaller objects, but the cost added by this conversion would be greater than any single rotation/translation would ever be.

**Comment by Moonire** [comment]
needed the same kind of algorithm so i came out with this. it does the job i think !
```
import numpy as np
from stl import mesh

mesh = mesh.Mesh.from_file('file_name.stl')
mesh = np.array(mesh)

a = []
for i in mesh:
	for n in range(3):
		a.append(tuple( i[3*n:3*n+2] ))

return list(set(a))
```

**Comment by carterbox** [comment]
For the sake of posterity and clarity. This problem can never be solved in `numpy-stl` because the STL format duplicates vertex information by design. Each face is recorded independently, so no vertex information is shared. Read more on [Wikipedia]( https://en.wikipedia.org/wiki/STL_(file_format)).

Other more concise mesh formats include PLY and OBJ.
