### ISSUE TITLE
can we merge 2 stl files such that they are overlapping, and we dont have to take care about overlapping traingles

### ISSUE THREAD

**Issue by haxer-max** [WoLpH/numpy-stl#167]

**Comment by WoLpH** [comment]
That sounds like concatenating the two meshes. That's easily done:
```python

new_mesh = mesh.Mesh(numpy.concatenate([
    mesh_a.data.copy(),
    mesh_b.data.copy(),
]))
```

**Comment by haxer-max** [comment]
@WoLpH ya but these doesn't really take care of intersection, lets say there are 2 cubes to be intersected side wise to create cuboid, the intersecting face of cube should get deleted, but it doesn't happen.

**Comment by WoLpH** [comment]
Very true, I assumed that was what you meant with not caring about overlapping triangles.
Properly merging meshes is a lot harder to do and a little outside of the scope of this library.

The big problem with merging meshes is that you need to create and destroy triangles within your mesh. Since this library is based on numpy arrays that's hard to do, beyond recreating.
