### ISSUE TITLE
Handling more than 1M triangles, when to use mesh.points

### ISSUE THREAD

**Issue by GriffinPrice** [WoLpH/numpy-stl#34]
Numpy-stl has been helping me quite a bit recently with some operations that I can't do in typical CAD programs. I've been mostly using it to parse STLs and then write my own algorithms to modify those files. It has been very helpful in this regard, and I am very thankful that you've already done most of the heavy lifting for playing with STLs in python.

I work with a lot of large (>1M triangle) meshes. I've gone into my stl.py file and raised the `MAX_COUNT` to higher numbers when it has been necessary, and I haven't had any problems when doing so. I was wondering why the 1M max triangle count was in place, and which limitations made that necessary. I'm doing simple 1-at-a-time vector manipulation, but I could understand that some of the fancier stuff will require more memory or computational load. 

Finally, when I request the iterable `mesh.points`, I expect an array of 1x3 arrays that is 3x the size of `mesh.vectors`. Instead, I get an array of the same size as `mesh.vectors` with 1x9 arrays. I was wondering what the rationale was for this, because I can't see a time when one would use `mesh.points` over `mesh.vectors`, since the latter is simply a better organized version of the former. Iterating over mesh.points doesn't actually iterate over all points, which seems odd to me, but I also understand that iterating over triangles makes sense for this sort of thing.

Thanks in advance for the help, and for creating such a brilliant module.

**Comment by WoLpH** [comment]
> I work with a lot of large (>1M triangle) meshes. I've gone into my stl.py file and raised the MAX_COUNT to higher numbers when it has been necessary, and I haven't had any problems when doing so. I was wondering why the 1M max triangle count was in place, and which limitations made that necessary. I'm doing simple 1-at-a-time vector manipulation, but I could understand that some of the fancier stuff will require more memory or computational load.

It was mostly an arbitrary chosen maximum as a safeguard. In some cases ascii files can be incorrectly recognized as binary files and if that happens it could very well be that you get an enormous data structure. While 1M triangles is not that much, having 1G or more takes some time and might cause memory issues. 
It might be a good idea to increase the maximum a bit as it's obviously a bit too low. You're actually the 2nd person that has reported this so I'll increase it to 100M. That should be enough for most people without killing too many machines in the process ;)

> Finally, when I request the iterable mesh.points, I expect an array of 1x3 arrays that is 3x the size of mesh.vectors. Instead, I get an array of the same size as mesh.vectors with 1x9 arrays. I was wondering what the rationale was for this, because I can't see a time when one would use mesh.points over mesh.vectors, since the latter is simply a better organized version of the former. Iterating over mesh.points doesn't actually iterate over all points, which seems odd to me, but I also understand that iterating over triangles makes sense for this sort of thing.

That's actually just a numpy performance issue. Both the `vectors` and `points` are simply views for the `data` attribute of a mesh which means they have no performance impact since all data can be modified in-place. I would have preferred a `1x3xN` instead of a `1x9x(N/3)` array but I haven't been able to find a way to create a numpy view that way.

Since changing it at this point would break backwards compatibility I can't say that I've investigated it any further. Depending on what you need to do the current method still has some merit though. You can still easily modify all points in the mesh or just all points on the X axis, for example:
```
# Increment all points on the Z axis by 1
your_mesh.points[:, 2::3] += 1
```
Which could be done easier using the Z view:
```
your_mesh.z[:] += 1
```

**Comment by WoLpH** [comment]
I've just deployed the new version with an increased maximum. That should be sufficient for the time being :)

**Comment by GriffinPrice** [comment]
> That's actually just a numpy performance issue. Both the vectors and points are simply views for the data attribute of a mesh which means they have no performance impact since all data can be modified in-place. I would have preferred a 1x3xN instead of a 1x9x(N/3) array but I haven't been able to find a way to create a numpy view that way.

What I have been doing in mine is adding the line `self.points = [item for sublist in data['vectors'] for item in sublist]`. There is some performance hit on declaration, but the new `points` is iterable and references the same data as `vectors`.

If you wanted to make this change and make it backwards compatible, you could always introduce a new attribute, like "vertices".

**Comment by WoLpH** [comment]
In that case a slightly easier (and probably faster) way to create the points would be to use zip: `list(zip(x.vectors))` which generates the same results :)

You shouldn't underestimate the cost of this operation though. I've run a few tests using the following example code:
```
import stl


@profile
def test():
    mesh = stl.Mesh.from_file('test.stl')
    print(mesh.vectors.shape)
    points = [item for sublist in mesh.data['vectors'] for item in sublist]
    print(len(points))


if __name__ == '__main__':
    test()
```

When running it with a file that has ~750k triangles it triples the memory usage:
```
# python -m memory_profiler test.py
(707086, 3, 3)
2121258
Filename: test.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   39.090 MiB    0.000 MiB   @profile
     5                             def test():
     6  102.641 MiB   63.551 MiB       mesh = stl.Mesh.from_file('stlMidpoint.stl')
     7  102.645 MiB    0.004 MiB       print(mesh.vectors.shape)
     8  290.934 MiB  188.289 MiB       points = [item for sublist in mesh.data['vectors'] for item in sublist]
     9  290.934 MiB    0.000 MiB       print(len(points))
```

And it's more than 10 times as slow:
```
# kernprof -l test.py
(707086, 3, 3)
2121258
Wrote profile results to test.py.lprof

# python -m line_profiler test.py.lprof
Timer unit: 1e-06 s

Total time: 1.74281 s
File: test.py
Function: test at line 4

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     4                                           @profile
     5                                           def test():
     6         1       126526 126526.0      7.3      mesh = stl.Mesh.from_file('stlMidpoint.stl')
     7         1           62     62.0      0.0      print(mesh.vectors.shape)
     8         1      1616176 1616176.0     92.7      points = [item for sublist in mesh.data['vectors'] for item in sublist]
     9         1           44     44.0      0.0      print(len(points))
```

**Comment by GriffinPrice** [comment]
Touche, I see why it isn't advisable. Numpy-stl is supposed to be fast, and it is a slow change. If I need this sort of functionality, I'll program it at a higher level than the module files.

As for the memory increase, is that just due to the fact that all triangles are actually being referenced, or is it copying data? I thought that since the mesh.points was still properly mutable, it was referencing the same data and should therefore only increase in size by 8bytes/point*3points/triangle*Ntriangles (8 bytes being the size of a pointer on an 64-bit system). Are numpy-arrays hiding some data that I don't see?

**Comment by WoLpH** [comment]
I've found a fairly fast and efficient way of creating a new (not referencing) points array:
```
points = numpy.concatenate((mesh.v0, mesh.v1, mesh.v2), axis=1)
```

As for the memory increase, it's mostly due to Python actually. You are creating a Python array with many items and every item is a reference to a Python object. Every Python object takes quite a lot of memory as well. Numpy is very efficient in terms of storage internally but Python is not that straightforward.

To illustrate:
```
# python -m memory_profiler test.py
float64 (1048576,)
1048576
1048576
Filename: test.py

Line #    Mem usage    Increment   Line Contents
================================================
     5   38.672 MiB    0.000 MiB   @profile
     6                             def test():
     7   38.672 MiB    0.000 MiB       n = 1048576
     8   46.688 MiB    8.016 MiB       x = numpy.random.rand(n)
     9   46.691 MiB    0.004 MiB       print(x.dtype, x.shape)
    10   72.684 MiB   25.992 MiB       y = [numpy.random.rand() for i in range(n)]
    11   72.684 MiB    0.000 MiB       print(len(y))
    12   97.727 MiB   25.043 MiB       z = [random.random() for i in range(n)]
    13   97.727 MiB    0.000 MiB       print(len(z))
```

You can read a little bit more about memory management in my book: https://www.safaribooksonline.com/library/view/mastering-python/9781785289729/ch12s06.html
I should note that it's just a small subsection though.
