### ISSUE TITLE
STL files containing multiple solids

### ISSUE THREAD

**Issue by Ghostkeeper** [WoLpH/numpy-stl#64]
We're seeing some STL files in the wild that have multiple solids in them. The one we were pointed to is here: https://www.thingiverse.com/thing:1322352

The file in question essentially has the following format:

    solid ascii
        ... <lots of facets>
    endsolid
    solid ascii
        ... <lots of facets>
    endsolid

numpy-stl loads only the first of the solids in the file.

The only STL file format specification I could find doesn't mention that this is allowed: http://www.fabbers.com/tech/STL_Format
However as these files are going around on the internet, you could consider loading them. I would expect them to load as if all facets are in the same solid.

**Comment by Ghostkeeper** [comment]
I made a minimum working example of two tetrahedra here:
[Tetrahedra.zip](https://github.com/WoLpH/numpy-stl/files/1562443/Tetrahedra.zip)

**Comment by WoLpH** [comment]
(cross posting from the downstream bug report)
It's actually supported but it requires a different call (since it's not returning a single mesh but multiple meshes): http://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.from_multi_file

It's essentially the same as the `from_file` method but it yields multiple meshes:

```python
from stl import mesh

for m in mesh.Mesh.from_multi_file('some_file.stl'):
    pass
    # process the mesh object here
```
