### ISSUE TITLE
How to deal with the negative diagonal elements of the inertia matrix?

### ISSUE THREAD

**Issue by onionsflying** [WoLpH/numpy-stl#69]
I have such a STL model:
https://github.com/hans-robot/elfin_robot/blob/master/elfin_description/meshes/elfin5/elfin_link6.STL

When I calculate the inertia matrix, I got results as follows:

Volume: 0.000147312401871
Center of gravity: [-0.00092366 -0.10107767 -0.0003367 ]
Inertia matrix:
[[ -6.36055479e-07   9.34708232e-09  -2.88727829e-09]
 [  9.34708232e-09   1.95924205e-07   4.32968570e-09]
 [ -2.88727829e-09   4.32968570e-09  -6.35165674e-07]]

There are two problems:
1. The center of gravity is at the outside of the mesh
2. There are two negative diagonal elements in inertia matrix

Could someone tell me how to deal with these problems?

**Comment by WoLpH** [comment]
@uvar perhaps you can help?

**Comment by Uvar** [comment]
[elfin_link6.zip](https://github.com/WoLpH/numpy-stl/files/1790644/elfin_link6.zip)

Could you try this version of the same STL?

**Comment by onionsflying** [comment]
Thanks for the reply. I tried to solve the problem, too. 

[elfin_link6_new.STL.zip](https://github.com/WoLpH/numpy-stl/files/1791767/elfin_link6_new.STL.zip)
You may try this STL. I moved the mesh 0.05m along Y axis and got positive results.

Volume: 0.000147312401202
Center of gravity: [-0.00092366  0.0073086  -0.0003367 ]
Inertia Matrix:
[[  1.94072019e-07   1.40262455e-09  -2.88727828e-09]
 [  1.40262455e-09   1.95924205e-07   4.97940183e-11]
 [ -2.88727828e-09   4.97940183e-11   1.94961824e-07]]

Is it a bug or something?

**Comment by Uvar** [comment]
In short, your STL is, and was, flawed. Mathematical operations on a non-closed mesh will invariantly lead to "weird" results.

In the accompanying zip the following is included:

- original STL
- logfile of some rather old python 2 code to fix STLs. Not sure if still 100% correctly working, but idea should be clear. 
- output STL of the old file.*
- STL fixed by other means. This algorithm produces even more new polygons (some 18k-ish). Probably better fix if you want to print it later on.

To be on the safe side, I tested this on your translated STL as well, exact same log as the one attached. The big red flag of something being wrong was that the center of gravity for the y axis was not moved by the 0.05m you suggested. 

*: output log of the output stl:
Reading from out.stl
15838
15838
The oriented area constitutes: [  1.69686610e-06   1.30723274e-06  -3.53794126e-06]
The mesh appears to be in proper order
the execution time was 0.04 seconds
[elfin_link.zip](https://github.com/WoLpH/numpy-stl/files/1792722/elfin_link.zip)

**Comment by WoLpH** [comment]
Thanks for the help @Uvar :)
I'm wondering how we can easily test for this (without too much impact) so we can display a big red warning :P

**Comment by Uvar** [comment]
A rather lazy test on an stl object is:

```
    def area_or(self):
        v0 = self.data['vectors'][:, 0]
        v1 = self.data['vectors'][:, 1]
        v2 = self.data['vectors'][:, 2]
        normals = numpy.cross(v1 - v0, v2 - v0)
        normals_sum = numpy.array([math.fsum(normals[:, 0]),
                                   math.fsum(normals[:, 1]),
                                   math.fsum(normals[:, 2])])
        return normals_sum
```
(forgive the ugly function, but its purpose should be clear)

If the oriented area yields in any dimension a number greater than you can expect from cumulative floating point errors, typically I'd flag anything above 1E-4, something is generally wrong. 

The correct way to go about it, is to construct a complete check for mesh closedness. I think I've got a paper written somewhere on how to recognize and categorize mesh flaws. I can also refactor the old code to yield a function `check_mesh_validity` which does nothing to repair it, just tells you whether the mesh was valid.

**Comment by onionsflying** [comment]
Thanks a lot for the detailed explanation. @Uvar

**Comment by wil3** [comment]
My goal was to use this library over Meshlab for computing inertia values. For my mesh I received the error pointing me here. The center of gravity looks fine however the output is,
```
[ 1.17503187e+08 -8.95833333e-02  2.73437500e-03]
[-8.95833333e-02  8.28535965e+07  5.92231632e-02]
[2.73437500e-03 5.92231632e-02 1.90830689e+08]
```

For Meshlab I get, 
```
 | 117503192.000000   2.947061   0.000000 |
 |  2.947061  82853608.000000   0.000000 |
 |  0.000000   0.000000  190830704.000000 |

Could someone help explain why they are different? In numpy-stl Ixy and Iyx are negative. Is Meshlab able to handle holes in the model while numpy-stl cannot? Any help would be greatly appreciated, this is not my area of expertise. I've attached the STL. 
[frame_floss2.zip](https://github.com/WoLpH/numpy-stl/files/2946283/frame_floss2.zip)
