### ISSUE TITLE
Export Mesh as 360 Images

### ISSUE THREAD

**Issue by thecortex** [WoLpH/numpy-stl#73]
Is there a feature to convert the 3D mesh into individuals images for each angle of the 360 views?

**Comment by WoLpH** [comment]
There's no image export feature at all, but it's easy enough to link up matplotlib:
https://github.com/WoLpH/numpy-stl/blob/develop/README.rst#plotting-using-matplotlib-is-equally-easy
```python
from stl import mesh
from mpl_toolkits import mplot3d
from matplotlib import pyplot

# Create a new plot
figure = pyplot.figure()
axes = mplot3d.Axes3D(figure)

# Load the STL files and add the vectors to the plot
your_mesh = mesh.Mesh.from_file('tests/stl_binary/HalfDonut.stl')
axes.add_collection3d(mplot3d.art3d.Poly3DCollection(your_mesh.vectors))

# Auto scale to the mesh size
scale = your_mesh.points.flatten(-1)
axes.auto_scale_xyz(scale, scale, scale)

# Show the plot to the screen
pyplot.show()
```

Instead of `pyplot.show()` you'll want to call `savefig`: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html

**Comment by thecortex** [comment]
Thank you
