### ISSUE TITLE
get_mass_properties unreliable

### ISSUE THREAD

**Issue by zarmomin** [WoLpH/numpy-stl#74]
I ran get_mass_properties() on the cube from the "Modifying Mesh objects" example (https://github.com/WoLpH/numpy-stl#modifying-mesh-objects) and it reported 0.0 volume and subsequent failures on the cog and moment of inertia calculations.

**Comment by WoLpH** [comment]
It definitely doesn't work for all cases but I'm not entirely sure what does and does not work. If ayone knows an algorithm that's more reliable feel free to create a pull request or point me towards it :)

**Comment by Uvar** [comment]
You ran get_mass_properties() on the "cube" from the modifying example. Sure thing, but did you finish the cube?

In the example, only 3 out of 6 faces, in other words a half-cube is made.
The volume of such an object is probably (luckily) correctly calculated: 0.0
How else would you calculate the volume of an open collection of surfaces?

![image](https://user-images.githubusercontent.com/9106009/38987358-b064c618-43cf-11e8-8101-c1f2d8fb2045.png)

**Comment by zarmomin** [comment]
@Uvar This is the code I ran, it does include the full cube
`from stl import mesh
import math
import numpy

# Create 3 faces of a cube
data = numpy.zeros(6, dtype=mesh.Mesh.dtype)

# Top of the cube
data['vectors'][0] = numpy.array([[0, 1, 1],
                                  [1, 0, 1],
                                  [0, 0, 1]])
data['vectors'][1] = numpy.array([[1, 0, 1],
                                  [0, 1, 1],
                                  [1, 1, 1]])
# Right face
data['vectors'][2] = numpy.array([[1, 0, 0],
                                  [1, 0, 1],
                                  [1, 1, 0]])
data['vectors'][3] = numpy.array([[1, 1, 1],
                                  [1, 0, 1],
                                  [1, 1, 0]])
# Left face
data['vectors'][4] = numpy.array([[0, 0, 0],
                                  [1, 0, 0],
                                  [1, 0, 1]])
data['vectors'][5] = numpy.array([[0, 0, 0],
                                  [0, 0, 1],
                                  [1, 0, 1]])

# Since the cube faces are from 0 to 1 we can move it to the middle by
# substracting .5
data['vectors'] -= .5

cube_back = mesh.Mesh(data.copy())
cube_front = mesh.Mesh(data.copy())

# Rotate 90 degrees over the X axis followed by the Y axis followed by the
# X axis
cube_back.rotate([0.5, 0.0, 0.0], math.radians(90))
cube_back.rotate([0.0, 0.5, 0.0], math.radians(90))
cube_back.rotate([0.5, 0.0, 0.0], math.radians(90))

cube = mesh.Mesh(numpy.concatenate([
    cube_back.data.copy(),
    cube_front.data.copy(),
]))

volume, cog, inertia = cube.get_mass_properties()`

**Comment by Uvar** [comment]
So, when looking at the "cube", I nearly had an heart attack.. :)

Out of the 12 polygons, 8 were wrongly defined. The following properties are obtained if you flip polygons `[0,1,2,5,6,7,8,11]`
print(volume, cog, inertia, sep='\n')
1.0
[ 0.  0.  0.]
[[ 0.16666667 -0.         -0.        ]
 [-0.          0.16666667 -0.        ]
 [-0.         -0.          0.16666667]]

And the worst part is, for such a theoretical exercise as a cube created from 2 identical  half-cubes, my in-built check for the oriented area does not find anything wrong, as was postulated  in my paper to be one of the failure modes...

Anyway, the `get_mass_properties` function is very stable if the mesh is mathematically sound. We keep running into trouble with improper meshes, so maybe we should actually find some time and build a `mesh_checker` module which runs either at initialization, or runs and throws an exception when trying to run mathematic operations on an improper mesh definition. :)

@WoLpH : please fix the mesh faces in the example code. the point ordering makes polygons `[0,1,2,5]` inward-facing, hence invalid when continuing down the road with a closed mesh.

**Comment by WoLpH** [comment]
Ok... makes sense that it's not working because of that. I'm just wondering if there might be a different solution where the face direction doesn't matter.

For this specific test it's easy to fix but I'm more worried about the general case, this probably happens more often

**Comment by Uvar** [comment]
It is the main idea behind the file format that all the information can be retrieved from the point cloud itself. Don't think it is easily fixed. In this particular case I am able to automatically fix it to the point of having volume = -1. , and the inertia matrix having a diagonal structure with negative elements. This is due to the fact that it cannot detect the failure mode of having symmetrical surfaces completely inwards-facing both. The perfection of failure is an outlier case we'll have to accept unless we construct a shrinked hull wrapper and compare each polygon normal with the hull local normal.

**Comment by Uvar** [comment]
It has to do with the way the area orientation (and hence abstractions to volume and the like) are calculated in STL format. The points in a polygon span half a parellelogram by its two vectors. Basically, inverting the point order leads to the area orientation to be "inwards" instead of outwards. To have it be 'valid', one should take care to have the point ordering follow the so-called 'right-hand-rule', to which I'm sure you can find a lot of online material if you combine it with the keyword 'vector cross product'.

As extra background reading material I added the relevant chapter from an old working paper:

[STL flaws.pdf](https://github.com/WoLpH/numpy-stl/files/1976880/STL.flaws.pdf)

**Comment by tpchuckles** [comment]
so in summary, for any surface, the cross product of two vectors ought to point outwards? seems reasonable. A bonus I suppose, in the process of debugging this, I found some of my surfaces were linear (all vertices appearing on a line, surface area of zero), which throws a monkeywrench into the works too. 
I fixed both of these issues in my meshes (well, fixed my capping function, and wrote a "fix orientation" function (which makes use of a ray-tracing function I wrote, seeing how many surfaces a given normal will intersect)) and it looks good now.
thanks! 
(and let me know if you want me to share my code. it's not beautiful or fast, but it does the job at least).

**Comment by Uvar** [comment]
The examination of triangles against their neighbours is fine, but an iterative process and not necessarily fast. (if you have a patch of inverted polygons, you'll end up flipping them bit by bit)

@WoLpH : Maybe instead of trying to fix the issues, we can at least plant a flag warning users something is wrong.

the quick check I always use is the sum of oriented areas. (closed surfaces with correct normals should have a net oriented area of 0 in all dimensions)
A bit more expensive test, but virtually guaranteed to find mesh flaws:

- Construct edge list (triangle abc has edges ab, bc and ca)
- Copy+flip (add edges ba, cb and ac to list)
- Verify each edge entry appears exactly twice in the list

As described in the document under the link in above contribution, this extended edge list can also be used to classify flaws if you want to take it to the next level, but for just alerting to the fact something is off about the STL specification; this much is enough.

**Comment by WoLpH** [comment]
@Uvar I've actually added a simple check based on your suggestion some time ago: https://github.com/WoLpH/numpy-stl/blob/86d2a0fc3def1f96563791a4e51713cc5cd12ca3/stl/base.py#L327-L336

A more advanced check would be useful but I'm not really sure how to write one, linear algebra has never been my forte

**Comment by tpchuckles** [comment]
Yeah Uvar, if your goal is simply detection, then my "compare against neighbors" is a bit excessive. that said, repairing isn't that much more from your second test method: use your edge list (before copying+flipping, each edge should appear exactly once) and the bad values in it to flip the bad faces. 

As for "iterative", i'm not sure if you mean "you must examine each surface" or "you must make multiple passes", although if you're smart about how you pass over the surfaces, you still only have to check (and possibly flip) each surface once.

**Comment by tpchuckles** [comment]
Ah, my apologies, I suppose I misunderstood what you were aiming for with the lists of edges. (You were thinking edge tracing, I was thinking surfaces while maintaining that list of edges). here's a better explanation of what I did: 
make a list of "surfaces we assume to be oriented" and "neighbor surfaces we have yet to examine", and make one pass to create an index of edges to surfaces.
in a second pass: 1) Pick any surface, and assume it to be correctly oriented. add its neighbors to the "to examine" list. 2) jump to any neighbor, and compare it (via edge orientation) against the oriented surface (the one we just came from, OR any of this surface's neighbors that are on the "oriented" list). flip it if necessary, add to the "oriented" list, and add this surfaces neighbors to the "to examine" list if they're not already oriented. All surfaces on the "oriented" list are oriented with respect to each other, and all surfaces on the "to examine" list have not been oriented, but have at least one neighbor who has. 3) repeat, only ever jumping to surfaces that have not been examined. 

And yes, as you mentioned, this fix relies on not having other issues in the mesh. For example, this fails with:
Entire body is inside-out:
we made the assumption that the first surface was oriented, so in the case of starting on an inverted surface, you end up with the whole thing inside-out, but this won't be caught by summing all orientations either. For other patches of inverted triangles, you'll simply flip each one one at a time. 
Edges shared by 0 or more than 2 surfaces: (open body, duplicated surfaces, etc)
Take a closed body and remove one surface. my method will have a problem with this, since asking "which surface is my neighbor, sharing this edge" on one of the surfaces next to the hole will fail. 
Multi-surface bodies:
if you can't walk from one surface to any other surface in the entire mesh, this will fail, as you either won't find all surfaces, or won't have a reference from one surface to the other (in a file with two spherical meshes next to each other, you may end up with one inside out, etc).
