### ISSUE TITLE
Identifying a similar face on 2 objects.

### ISSUE THREAD

**Issue by mperino** [WoLpH/numpy-stl#92]
I'm looking at creating a tool to join two STL based on their most similar face. There are a lot of complex tools that require manual intervention to join 2 STL, but none that I'm aware of that do a simple rotate & translate to join 2 stl based on their most similar face.   I've done a bunch with the example code that is provided, but any tips or ideas on what I'm trying to accomplish?  Especialy how to iterate over a list of faces in the the stl?

**Comment by mperino** [comment]
So I'm getting further, but because I'm just scratching the surface, perhaps I'm going in the wrong direction.  mesh.area seems really quick as a way to compare two mesh's.  I can compare 2x 256K .stl in 7 seconds.  

My thoughts are to refine this and functionalize it to find the two mesh's with the largest same area. 

Anyone with more experience have any reccomendations?  


=====================POC Code Bellow===================
from stl import mesh

# Using an existing stl file:
mesh_one = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body1.stl')
mesh_two = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body2.stl')
min_match_area = 100

match_count = 0

for mesh_area_one in mesh_one.areas:
    for mesh_area_two in mesh_two.areas:
        if mesh_area_one == mesh_area_two and mesh_area_one > min_match_area:
            print ("Mesh match:{0}, {1}".format(mesh_area_one, mesh_area_two))
            match_count = match_count + 1

print("There were {0} matching Mesh areas".format(match_count))

**Comment by WoLpH** [comment]
That algorithm can easily be rewritten using numpy operations, making it _much_ faster:

```python
from stl import mesh

# Using an existing stl file:
mesh_one = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body1.stl')
mesh_two = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body2.stl')
min_match_area = 100

match_count = 0

areas = mesh_one.areas[mesh_one.areas == mesh_two.areas]
large_areas = areas[areas > min_match_area]
match_count = large_areas.size

for area in large_areas:
    print ("Mesh match:{0}".format(area))

print("There were {0} matching Mesh areas".format(match_count))
```

**Comment by mperino** [comment]
Interesting.. but that didnt work for me.  areas gets assigned an empty set.
It looks like every mesh in a .stl is 3 points and a vector. Each face is made up of a tessellation of many of these.  So Now im looking for some operations to work on "Faces".  Im going to have to think more on this, as I naively assumed that each face was a single set of points.  
What's clear is I have a bunch more reading to do!

**Comment by WoLpH** [comment]
Now that I think of it, my code is different indeed. It's comparing the arrays by comparing each item from array 1 with a single item from array 2 instead of all of them at the same time.

Having that said, for this case there's a fairly easy solution I think. Simply do a set conversion and calculate the intersection (assuming duplicates are not relevant here) :)

```python
from stl import mesh

# Using an existing stl file:
mesh_one = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body1.stl')
mesh_two = mesh.Mesh.from_file('/home/mperino/3d/Models/glue_test/body2.stl')
min_match_area = 100

match_count = 0

areas_one = set(mesh_one.areas[mesh_one.areas > min_match_area])
areas_two = set(mesh_two.areas[mesh_two.areas > min_match_area])
areas = areas_one & areas_two
match_count = len(areas)

for area in areas:
    print ("Mesh match:{0}".format(area))

print("There were {0} matching Mesh areas".format(match_count))
```

**Comment by Uvar** [comment]
This works quite well if you have objects of which you know upfront that by design there should be similar faces. If you have objects subject to floating point variations (can happen in any software suite) / noise (3D scan) or even completely independently designed objects (although then I wouldn't necessarily know why you'd want to glue them together), you will have to allow for some tolerance which disqualifies using `sets`. Maybe `sets` can still be used if you convert internal storage to `ints`?

However, in case of this not being so, you will have to define a similarity/joinability score. Probably based on aspect ratio/dimension sizes. I can see this being a pretty difficult task.

One check I am missing here, is to verify the triangle you currently want to join on is actually part of the convex hull. I am certain you will end up with quite brilliant meshes if you try to join based on some concave face .. ;)
That being said, if you want to join on faces rather than triangles, one way you could try to go is to determine the orientations in your convex hull; then aggregate the "face" area by comparing unit normals of triangles to that of the face. Also might allow for some more elaborate glueing in some cases; where instead of entire faces, corner points could be adjoined.

From the perspective of mesh validity, I'd warn that back-to-back faces are not valid in a pure STL definition. Do you plan to remove the faces being adjoined, potentially requiring vertex matching to be sure the mesh won't become opened, or just treat the two as 2 separate STLs, but for any other purpose adjoined?
