### ISSUE TITLE
please consider renaming the argument to 'vector' instead of 'matrix'

### ISSUE THREAD

**Issue by komahanb** [WoLpH/numpy-stl#98]
https://github.com/WoLpH/numpy-stl/blob/1cb4c5013c9b5a2dee0500e06b574ee0f4d19ca3/stl/base.py#L491

**Comment by WoLpH** [comment]
It's not a single vector though so that would not be accurate

Since every triangle consists of 3 points this returns a list with the length being equal to the amount of triangles in your mesh: https://github.com/WoLpH/numpy-stl/blob/1cb4c5013c9b5a2dee0500e06b574ee0f4d19ca3/stl/base.py#L500

The loop is to get through all 3 points of the triangle

**Comment by komahanb** [comment]
You are right. Thanks for the clarification.
